version: 2

models:
  - name: clean_bike_rides
    description: "dados de passeio de bicicleta"
    columns:
      - name: total_minutes
        description: ""
      - name: total_bike_hires
        description: ""
      - name: average_duration
        description: ""
      - name: month
        description: ""
      - name: start_peak_travel
        description: ""
      - name: same_station_flag
        description: ""
      - name: start_station_id
        description: ""
      - name: start_station_name
        description: ""
      - name: end_station_id
        description: ""
      - name: end_station_name
        description: ""